name: AutoDeploy

# Triggers deployment of code to test servers
on:
  workflow_call:
    # inputs: will be the various git ones
    inputs:
      git_repo:
        description: "The github repository to act on"
        required: false
        default: ${{github.repository}}
        type: string
    secrets:
      token:
        description: "Token sent to service to authorize deployment"
        required: true
      servers:
        description: "Comma separated list of servers to contact"
        required: true

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - id: "Output_vars"
        run: echo "Repo is ${{inputs.git_repo}}"
      - id: "Inherited"
        run: echo "Inhirit ${{github.repository}}"
