name: AutoDeploy

# Triggers deployment of code to test servers
on:
  workflow_call:
    # inputs: will be the various git ones
    inputs:
      git_repo:
        description: "The github repository to act on"
        required: false
        default: ${{github.repository}}
        type: string
      git_banch:
        description: "The branch the commit is on"
        required: false
        default: ${{github.ref_name}}
        type: string
      git_sha:
        description: "SHA of commit"
        required: false
        default: ${{github.sha}}
        type: string
      git_actor:
        description: "The user making ht commit"
        required: false
        default: ${{github.actor}}
        type: string
      git_owner:
        description: "The owner/organization of repository"
        required: false
        default: ${{github.repository_owner}}
        type: string

    secrets:
      server_token:
        description: "json string of server:key"
        required: true

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - id: "Output_vars"
        run: echo "Repo is ${{inputs.git_repo}} sha is ${{inputs.git_sha}} actor is ${{inputs.git_actor}} branch is ${{inputs.git_banch}} ownser is ${{inputs.git_owner}}"
